name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Install pip 24.2 and dependencies
      run: |
        python -m pip install --upgrade pip==24.2
        pip install -r backend/requirements.txt

    - name: Run Tests and Coverage
      run: |
        cd backend
        coverage run -m pytest
        coverage report --fail-under=100

    - name: Lint the code (80%+ threshold)
      run: |
        pylint . --rcfile=./backend/.pylintrc | tee pylint_report.txt
        grep -oP "(?<=Your code has been rated at )\d+\.\d+" pylint_report.txt | awk '{if ($1 < 8.0) exit 1}'

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Send Approval Email
      run: |
        echo "CI build passed. Approve to push changes to GitHub." | mail -s "Approval Needed: Push to GitHub" 1vladislavzhigulin@gmail.com

  wait-for-approval:
    needs: notify
    runs-on: ubuntu-latest
    steps:
    - name: Wait for approval
      run: |
        read -p "Have you approved the push to GitHub? (yes/no): " approval
        if [ "$approval" != "yes" ]; then
          exit 1
        fi

  push-to-github:
    needs: wait-for-approval
    runs-on: ubuntu-latest
    steps:
    - name: Push to GitHub
      run: |
        git push origin main
